from django.urls import path
from . import views
from . import resume
urlpatterns=[
    path('home',views.home,name="home"),
    path('',views.home,name="home"),
    path('signup',views.signup_view,name="signup"),
    path('login',views.login_view,name="login"),
    path('logout',views.logout_view,name="logout"),
    path('settings',views.settings,name="settings"),
    path('like_post',views.like_post,name="like_post"),
    path('profile/<pk>',views.profile_views,name="profile"),
    path('delete_post/<str:id>',views.delete_post,name="delete_post"),
    path('follower',views.check_follower,name="follower"),
    path('resume',views.resume,name="resume"),
    path('username_suggestions/', views.username_suggestions, name='username_suggestions'),
    path('professionalprof',resume.professionalprof,name="professinalprof"),
    path('projects',resume.projects,name="projects"),
    path('internship',resume.internship,name="internship"),
    path('favpost/<uuid:post>',views.favpost_add,name="favpost_add"),
    path('favpost',views.favpost,name="favpost"),
    path('delete_favpost/<int:pk>',views.delete_fav,name="delete_favpost"),
    path('profile-analytics',resume.profprofile,name="profile_analytics"),
    path('show/education',resume.showEducation,name="showeducation"),
    path('add/education',resume.addeducation,name="addeducation"),
    path('update/education/<int:pk>',resume.updateeducation,name="updateeducation"),
    path('delete/education/<int:pk>',resume.deleteedu,name="deleteedu"),
    path('show/project',resume.showProject,name="show-project"),
    path('add/project',resume.addProject,name="add-project"),
    path('update/project/<int:pk>',resume.updateproject,name="update-project"),
    path('delete/project/<int:pk>',resume.deleteproject,name="delete-project"),
    path('show/internship',resume.showIntern,name="show-intern"),
    path('update/intern/<int:pk>',resume.updateIntern,name="update-intern"),
    path('add/intern',resume.addIntern,name="add-intern"),
    path('delete/intern/<int:pk>',resume.deleteIntern,name="delete-intern"),
    path('show/certification',resume.showCertification,name="show-cert"),
    path('update/certification/<int:pk>',resume.updateCertification,name="update-cert"),
    path('add/certification',resume.addCertification,name="add-cert"),
    path('delete/certification/<int:pk>',resume.deleteCertification,name="delete-cert"),
    path('show/achivements',resume.showAchivements,name="show-achive"),
    path('update/achivements/<int:pk>',resume.updateAchivements,name="update-achive"),
    path('add/achivements',resume.addAchivements,name="add-achive"),
    path('delete/achivements/<int:pk>',resume.deleteAchivements,name="delete-achive"),
]