# Generated by Django 4.2.6 on 2023-12-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='no_of_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
