# Generated by Django 4.2.6 on 2023-12-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_followers_favorate_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
