# Generated by Django 4.2.6 on 2024-01-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_professional_profile_soft_skill_social_media_urls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional_profile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='professional_profile',
            name='profimg',
            field=models.ImageField(default=None, upload_to='prof_images'),
        ),
        migrations.AlterField(
            model_name='professional_profile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
