# Generated by Django 4.2.6 on 2024-01-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_professional_profile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='level',
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(default='Bechelores Degree', max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(default='Mechanical Engineering', max_length=200),
        ),
    ]
