# Generated by Django 4.2.6 on 2024-01-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_education_level_education_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(default="EX: Bechelor's", max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(default='EX: Business', max_length=200),
        ),
    ]
