# Generated by Django 4.2.6 on 2024-01-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_education_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivements',
            name='as_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='as_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='achivements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Achive_images'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='cert_img',
            field=models.ImageField(blank=True, null=True, upload_to='cert_image'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
