# Generated by Django 4.2.6 on 2024-01-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_achivements_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='level',
            field=models.CharField(choices=[('Elementery Proficiency', 'Elementery Proficiency'), ('Limited working Proficiency', 'Limited working Proficiency'), ('Professional working Proficiency', 'Professional working Proficiency'), ('Full Professional  Proficiency', 'Full Professional  Proficiency'), ('Native or bilingual Proficiency', 'Native or bilingual Proficiency')], default='read', max_length=200),
        ),
        migrations.AlterField(
            model_name='social_media_urls',
            name='link',
            field=models.URLField(),
        ),
    ]
