# Generated by Django 4.2.6 on 2024-01-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_languages_level_alter_social_media_urls_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profession',
            field=models.CharField(default='Software Engineer', max_length=225),
        ),
    ]
