# Generated by Django 4.2.6 on 2024-01-23 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_project_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(default="EX: Bachelor's", max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
