# Generated by Django 4.2.6 on 2024-01-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(default='bg.jpeg', upload_to='bg_images'),
        ),
    ]
