# Generated by Django 4.2.6 on 2024-01-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_profile_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestionSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
